function filter = AlphaBeta
%ALPHABETA Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 14-Nov-2013 17:41:39
%

Fstop1 = 5;    % First Stopband Frequency
Fpass1 = 8;    % First Passband Frequency
Fpass2 = 27;   % Second Passband Frequency
Fstop2 = 30;   % Second Stopband Frequency
Astop1 = 60;   % First Stopband Attenuation (dB)
Apass  = 1;    % Passband Ripple (dB)
Astop2 = 60;   % Second Stopband Attenuation (dB)
Fs     = 960;  % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

filter = design(h, 'equiripple', ...
    'MinOrder', 'any');



% [EOF]
